### GET request to example server
GET http://localhost:8080

### GET all engineers
GET http://localhost:8080/api/v1/software-engineers/list

### create new eng
POST http://localhost:8080/api/v1/software-engineers/new-eng
Content-Type: application/json

{
  "name": "John Doe",
  "techStack": "Java, Spring Boot, PostgreSQL"
}

### get by id
GET http://localhost:8080/api/v1/software-engineers/2

### delete by id
DELETE http://localhost:8080/api/v1/software-engineers/delete/2

### update by id
PUT http://localhost:8080/api/v1/software-engineers/2
Content-Type: application/json

{
  "name": "John Emile",
  "techStack": "React"
}